### ISSUE TITLE
Display price in the `item-properties`

### ISSUE THREAD

**Issue by InnilToo** [krbz999/zhell-custom-stuff#48]
![image](https://github.com/krbz999/zhell-custom-stuff/assets/33260912/40405738-9400-49f5-a50e-3bf6de1266be)

**Comment by krbz999** [comment]
This should be a request on the system repo, I feel.

**Comment by InnilToo** [comment]
https://github.com/krbz999/zhell-custom-stuff/issues/48 🫡

**Comment by krbz999** [comment]
PR submitted to the system.
